-- Create buckets manually in Supabase dashboard or via migration scripts.
-- compliance-private: private storage for faculty uploads.
-- submission-previews: derived preview artifacts.
-- review-attachments: evaluator file remarks.
-- exports-private: generated report exports.
